"""Add AzureApiKey table

Revision ID: a4c351672412
Revises: 6a41f534123a
Create Date: 2024-11-06 09:01:23.566346

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a4c351672412'
down_revision: Union[str, None] = '6a41f534123a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('azure_api_key',
    sa.Column('user', sa.Uuid(as_uuid=False), nullable=False),
    sa.Column('key_vault_identifier', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['user'], ['user.id'], ),
    sa.PrimaryKeyConstraint('key_vault_identifier')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('azure_api_key')
    # ### end Alembic commands ###
