// This file is auto-generated by @hey-api/openapi-ts

export type HTTPValidationError = {
  detail?: Array<ValidationError>;
};

/**
 * The base User schema to use in the API.
 */
export type User = {
  id: string;
  email: string;
  identity_provider: string;
  family_name: string;
  given_name: string;
  created_date: string;
};

export type ValidationError = {
  loc: Array<string | number>;
  msg: string;
  type: string;
};

/**
 * The base Workflow schema to use in the API.
 */
export type Workflow = {
  id: number;
  title: string;
  owner: number;
  created_date: string;
  schema?: {
    [key: string]: unknown;
  } | null;
};

/**
 * Data model to create a new Workflow
 */
export type WorkflowCreate = {
  title: string;
};

/**
 * Data model to update a Workflow
 */
export type WorkflowUpdate = {
  [key: string]: unknown;
};

export type GetSelfUserResponse = User;

export type GetSelfUserError = unknown;

export type GetWorkflowData = {
  path: {
    workflow_id: number;
  };
};

export type GetWorkflowResponse = Workflow;

export type GetWorkflowError = HTTPValidationError;

export type UpdateWorkflowData = {
  body: WorkflowUpdate;
  path: {
    workflow_id: number;
  };
};

export type UpdateWorkflowResponse = Workflow;

export type UpdateWorkflowError = HTTPValidationError;

export type DeleteWorkflowData = {
  path: {
    workflow_id: number;
  };
};

export type DeleteWorkflowResponse = unknown;

export type DeleteWorkflowError = HTTPValidationError;

export type GetWorkflowsResponse = Array<Workflow>;

export type GetWorkflowsError = unknown;

export type CreateWorkflowData = {
  body: WorkflowCreate;
};

export type CreateWorkflowResponse = Workflow;

export type CreateWorkflowError = HTTPValidationError;
